### ISSUE TITLE
[feature] multiple data sources

### ISSUE THREAD

**Issue by wichmann** [m-wichmann/local_seriesly#15]
Currently local_seriesly depends on only on source for its data, tvrage.com. That site is down since some days. So more data sources (e.g. tvmaze.com) should be added to get air dates etc.

**Comment by m-wichmann** [comment]
Fixed with a01a5683. Changed provider to tvmaze. The profile config has to be converted once (!) by calling 'local_seriesly.py -c'. Do not call this multiple times or the profile config will get wrecked. The solution is rather hacky, but should work for now.

**Comment by wichmann** [comment]
The command for converting the profile config is 'local_seriesly.py --convert'.
